const fs = require("fs");

// Загружаем исходный JSON
const data = require("./data1.json");

// Список глаголов
// const verbs = [
//   "accept",
//   "afford",
//   "agree",
//   "allow",
//   "announce",
//   "apologize",
//   "appear",
//   "arrive",
//   "ask",
//   "avoid",
//   "be",
//   "beat",
//   "become",
//   "begin",
//   "believe",
//   "borrow",
//   "break",
//   "bring",
//   "build",
//   "burn",
//   "buy",
//   "call",
//   "can",
//   "carry",
//   "catch",
//   "celebrate",
//   "change",
//   "check",
//   "choose",
//   "clean",
//   "climb",
//   "close",
//   "come",
//   "compare",
//   "complain",
//   "consider",
//   "cook",
//   "copy",
//   "correct",
//   "cost",
//   "continue",
//   "cover",
//   "cry",
//   "cut",
//   "dance",
//   "dare",
//   "decide",
//   "deliver",
//   "describe",
//   "develop",
//   "die",
//   "discover",
//   "discuss",
//   "divide",
//   "do",
//   "double",
//   "doubt",
//   "drag",
//   "draw",
//   "dress",
//   "drink",
//   "drive",
//   "drop",
//   "dry",
//   "eat",
//   "earn",
//   "enjoy",
//   "escape",
//   "expect",
//   "explain",
//   "fall",
//   "feed",
//   "feel",
//   "fight",
//   "fill",
//   "find",
//   "finish",
//   "fly",
//   "follow",
//   "force",
//   "forget",
//   "freeze",
//   "fry",
//   "get",
//   "give",
//   "go",
//   "grow",
//   "guess",
//   "happen",
//   "hate",
//   "have",
//   "hear",
//   "help",
//   "hide",
//   "hit",
//   "hold",
//   "hope",
//   "hurt",
//   "identify",
//   "imagine",
//   "improve",
//   "include",
//   "increase",
//   "introduce",
//   "invite",
//   "involve",
//   "join",
//   "jump",
//   "keep",
//   "kill",
//   "kiss",
//   "know",
//   "laugh",
//   "lead",
//   "learn",
//   "leave",
//   "lend",
//   "let",
//   "like",
//   "listen",
//   "live",
//   "look",
//   "lose",
//   "love",
//   "make",
//   "manage",
//   "marry",
//   "mean",
//   "measure",
//   "meet",
//   "miss",
//   "move",
//   "need",
//   "notice",
//   "obey",
//   "offer",
//   "open",
//   "organize",
//   "owe",
//   "own",
//   "pass",
//   "pay",
//   "perform",
//   "pick",
//   "plan",
//   "play",
//   "point",
//   "place",
//   "practice",
//   "prefer",
//   "prepare",
//   "present",
//   "pretend",
//   "prevent",
//   "produce",
//   "protect",
//   "prove",
//   "provide",
//   "pull",
//   "push",
//   "put",
//   "raise",
//   "reach",
//   "read",
//   "realize",
//   "receive",
//   "recognize",
//   "record",
//   "reduce",
//   "refuse",
//   "regret",
//   "relate",
//   "relax",
//   "remember",
//   "remove",
//   "repeat",
//   "replace",
//   "reply",
//   "report",
//   "require",
//   "return",
//   "ride",
//   "ring",
//   "rise",
//   "roll",
//   "run",
//   "remain",
//   "represent",
//   "save",
//   "say",
//   "see",
//   "seem",
//   "sell",
//   "send",
//   "serve",
//   "set",
//   "settle",
//   "shake",
//   "share",
//   "shoot",
//   "show",
//   "shut",
//   "sign",
//   "sing",
//   "sit",
//   "sleep",
//   "smile",
//   "solve",
//   "speak",
//   "spend",
//   "stand",
//   "start",
//   "stay",
//   "steal",
//   "stop",
//   "suggest",
//   "supply",
//   "support",
//   "suppose",
//   "surprise",
//   "swim",
//   "take",
//   "talk",
//   "teach",
//   "tell",
//   "tend",
//   "test",
//   "thank",
//   "think",
//   "throw",
//   "touch",
//   "train",
//   "travel",
//   "treat",
//   "try",
//   "turn",
//   "understand",
//   "use",
//   "visit",
//   "wait",
//   "walk",
//   "want",
//   "watch",
//   "wear",
//   "win",
//   "wish",
//   "work",
//   "worry",
//   "write",
//   "yell"
// ];

const verbs = ["she", "he", "we", "they", "you", "i", "will", "don`t", "doesn`t", "won't", "didn`t", "does" ]

// Функция для перемешивания массива
function shuffle(array) {
  return array.sort(() => Math.random() - 0.5);
}

// Обработка каждого элемента
for (const key in data) {
  const item = data[key];
  const existing = new Set(item.options);
  const additional = shuffle(verbs.filter(v => !existing.has(v))).slice(0, 1);
  item.options = shuffle([...item.options, ...additional]);
}

// Сохраняем результат
fs.writeFileSync("updated.json", JSON.stringify(data, null, 2), "utf-8");

console.log("Готово! Файл сохранён как updated.json");
